// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsBZrTaTP007UHGbO5SGGtSKqpyzbz9DA',
    appId: '1:995818480323:web:0d9896a1ed016c39603876',
    messagingSenderId: '995818480323',
    projectId: 'dsa-project-de1a6',
    authDomain: 'dsa-project-de1a6.firebaseapp.com',
    storageBucket: 'dsa-project-de1a6.firebasestorage.app',
    measurementId: 'G-QGNB9QLDJF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa7yxT7qzPp_pR2LbNhJUru8aMKkMUwv0',
    appId: '1:995818480323:android:5abefdd9075517e0603876',
    messagingSenderId: '995818480323',
    projectId: 'dsa-project-de1a6',
    storageBucket: 'dsa-project-de1a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClzrpbE4ubb5crjU6MN55aY8AElxZlTmc',
    appId: '1:995818480323:ios:050464f12cefae48603876',
    messagingSenderId: '995818480323',
    projectId: 'dsa-project-de1a6',
    storageBucket: 'dsa-project-de1a6.firebasestorage.app',
    iosBundleId: 'com.example.justiceforher',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClzrpbE4ubb5crjU6MN55aY8AElxZlTmc',
    appId: '1:995818480323:ios:050464f12cefae48603876',
    messagingSenderId: '995818480323',
    projectId: 'dsa-project-de1a6',
    storageBucket: 'dsa-project-de1a6.firebasestorage.app',
    iosBundleId: 'com.example.justiceforher',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsBZrTaTP007UHGbO5SGGtSKqpyzbz9DA',
    appId: '1:995818480323:web:eebb44dd6e322fff603876',
    messagingSenderId: '995818480323',
    projectId: 'dsa-project-de1a6',
    authDomain: 'dsa-project-de1a6.firebaseapp.com',
    storageBucket: 'dsa-project-de1a6.firebasestorage.app',
    measurementId: 'G-LLCCDP6W0S',
  );

}